### PR TITLE
Add vue3 support

### PR DESCRIPTION
**Pull request by judebourlay**
Make the frontend code work with `server.client_type = 'vue3'`
I did not tested this extensively for now.  
I'm going to future proof this in the next weeks/months.  
Marking as draft for now, I need to test if the switch between vue2/vue3 is happening correctly if relevant.  
It should not impact existing installation.

### CODE REVIEW

**Comment by jourdain** [comment]
Side note. Make sure your commit messages use semantic release syntax.

**Comment by Julesdevops** [comment]
CI is green

**Comment by judebourlay** [comment]
since trame now use vue3/vuetify3 by default, I updated the examples accordingly. Tested the 6 different examples and it seems to work properly

**Comment by jourdain** [comment]
ready for merging?

**Comment by judebourlay** [comment]
@jourdain I'll do a few more test today and it should be ready by the end of the day

**Comment by judebourlay** [comment]
Thank you for merging @jourdain !

**Pull request merged**
